ln -s bin_position_counts.py              bin_position_counts
ln -s common_length_distribution.py       common_length_distribution
ln -s error_nonuniformity_filter.py       error_nonuniformity_filter
ln -s event_matrix_to_rates.py            event_matrix_to_rates
ln -s fasta_length_distribution.py        fasta_length_distribution
ln -s fasta_match_length_distribution.py  fasta_match_length_distribution
ln -s harvest_trf_html.py                 harvest_trf_html
ln -s make_length_distribution_spec.py    make_length_distribution_spec
ln -s map_onto_simulated_reads.py         map_onto_simulated_reads
ln -s minimap2_cs_to_events.py            minimap2_cs_to_events
ln -s mock_motif_genome.py                mock_motif_genome
ln -s ncrf_cat.py                         ncrf_cat
ln -s ncrf_error_clumps.py                ncrf_error_clumps
ln -s ncrf_error_positions.py             ncrf_error_positions
ln -s ncrf_extract_event_matrix.py        ncrf_extract_event_matrix
ln -s ncrf_extract_mx_matrix.py           ncrf_extract_mx_matrix
ln -s ncrf_msa.py                         ncrf_msa
ln -s ncrf_read_simulator.py              ncrf_read_simulator
ln -s ncrf_resolve_overlaps.py            ncrf_resolve_overlaps
ln -s ncrf_sort.py                        ncrf_sort
ln -s ncrf_summary.py                     ncrf_summary
ln -s ncrf_to_bed.py                      ncrf_to_bed
ln -s ncrf_words.py                       ncrf_words
ln -s observed_vs_truth.py                observed_vs_truth
ln -s parameter_ball.py                   parameter_ball
ln -s random_normal.py                    random_normal
ln -s reconstruct_simulated_alignments.py reconstruct_simulated_alignments
ln -s sam_to_event_matrix.py              sam_to_event_matrix
ln -s spread_length_distribution.py       spread_length_distribution
ln -s sum_length_distributions.py         sum_length_distributions
ln -s truth_to_rates.py                   truth_to_rates
